### ISSUE TITLE
Redis connection timeouts while deployed on Azure

### ISSUE THREAD

**Issue by clemlesne** [microsoft/call-center-ai#407]
Even though I deployed the resources twice with the same basic config.yaml bellow, same commit, container version, same code - the application in the container did not work yesterday and it did work today.

I have had considerable difficulty with unexpected behaviour when I have set up everything multiple times.

[logs_working_remote.txt](https://github.com/user-attachments/files/18526529/logs_working_remote.txt)

https://github.com/user-attachments/assets/1a41a05d-9845-4800-9588-f72fc15de0ae

```
conversation:
  initiate:
    agent_phone_number: "+46700229902" # Phone number the bot will transfer the call to if customer asks for a human agent
    bot_company: Contoso
    bot_name: Amélie
    lang: {}

communication_services:
  phone_number: "+4532727047" # Phone number purshased from Communication Services

sms: {}

prompts:
  llm: {}
  tts: {}
```

_Originally posted by @Lovenoreus in https://github.com/microsoft/call-center-ai/issues/392#issuecomment-2610958915_

Logs:

```
2025-01-23T20:01:09.827183Z [info     ] Using Redis cache noreuscsgroupswe.redis.cache.windows.net:6380
2025-01-23T20:03:38.452282Z [error    ] Error requesting Redis
Traceback (most recent call last):
[...]
redis.exceptions.TimeoutError: Timeout connecting to server
```
